language: node_js
node_js:
- 8.9.0
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    rooms:
      secure: DxrPGmYS/e+vAT+6FB/IMV6uN+vQIv8NcoS0YEX5HUFIWa0EFtdm2Z6zB9p+oMhuvGMDfkZ4D7GyqFMJ604VHOFTn5e7trvP4aCVX3VchVQPi6XRkgfN9fuoJ16MgvqhfxqEeUGV0rSXjM6ztqH5WCtPYuhnSX7e1sOuWr5WqRWThh4YuOgRN6jo6fjTuRMnU7LavGkdRbhDdnzhBkZH3fWKhQ8u3ScjYPBaRNmdJdSO7ZfIrcESdr/IifO5Og/uhS9DIZaMRNH4+qcWGf3uCux31GoxJ501TxtBB4zua0uwK6FiDC3ooYSuFBR30D4klD6jhxdQKFVotNaUS4M98Btm8/q2cM45SFA0W2aqEfKShWLW34JLXL+kojdu72PfWFN0dJ5ST+3tVKB9TzyyXc3yZ/GPwZyxd1oX1oBUISEPO9jOsCNc7e1Su8VeSivXoyfWI83pmZPJj1u1CU3CGwC7TQxoKXqAxatkaofAaQDBISqfd4Tg1WDifcae2RDsbjwaeHdGas1Ng/cKx7XD+KRv1fba+5GWjHkzS3MxUcU7QVTicHvVOZXE9O6TshfNa5YVMvNb7m3B3xMX/EPPUSe7foN7CmWbpnqdNkJ+hJEpkXpAqaoVhX6lYOLViHxGuxfbToqw6+H7sATqNwJHb+Yk5gAAyzncFpUSIKRKIzY=
    on_success: never
    on_failure: always
    on_pull_requests: false
install:
  - npm install
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - npm prune
  - greenkeeper-lockfile-update
after_success:
  - npm run coveralls
  - npm run semantic-release
after_script:
  - greenkeeper-lockfile-upload
