language: node_js
node_js:
- 8.9.0
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    rooms:
      secure: IGDOx9X8wWdwCSVIb43rgyunulGz2/Zg4sj691+BZapg8TX8Wvc0RqkBJqwZUPaYJRld/pH40843+nGvg3/xr42UrlIM146dbc1zxcyiA6QbCwWP8e00tVHTUe39Ft0IfemKzISy3CrMBC02fCWBJGNnCU8VmHs5T6b3Kg9w7gnor9pMT9/KoviK0hxsponzzdNsA6+hPqVg2DxpxtRpc3komILdFn+I3MrBuHbsZozr4XWjydEuNjo9BMDV0w1knPRraKpUMLBJqVItdweISM4k1lnHrlalX3OfAgFu0+DpkNMraxsd6RdoDZV2hW5iyLg5IIr6U1+xvYwyQe9B+4wMD41WPx5Ykg2KAIMQ5Mmg2TjWFVj4NyBbbpuz0DhJuyR0i75dPd976xaCQaD85q17x6hFxUj5UluRr+sLx4aonb3NAha6Oz7BsGZ8ZNPxUMm5j7hwsIBHig/GAc+MR7Ts0BAVVOwetxH7VY52TDfaM3ThmrfuTcl9Ra/f10KV5eIdqNjz9uib37zl19Mb4li6uIC7DgTU8LflmTJBynLnAP4BTTqpEumeDy4PP2OvNdiWET79wNOCp5hs99FavXbRVt2kZT7y4I8cGIC8XRKKA7VxbuVv6QE2pjIOubE2vrxx7fl2PSClX9GSTDfdbD/rP+7LuKhxGOH+J/pnH6o=
    on_success: never
    on_failure: always
    on_pull_requests: false
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - npm prune
  - greenkeeper-lockfile-update
after_success:
  - npm run coveralls
  - npm run semantic-release
after_script:
  - greenkeeper-lockfile-upload
